-- noinspection SqlNoDataSourceInspectionForFile

CREATE SCHEMA TLA;

CREATE TABLE TLA.`USER` (
    USER_ID NUMBER AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR2(50),
    LAST_NAME VARCHAR2(50),
    EMAIL VARCHAR2(50),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
);

CREATE TABLE TLA.TODO_LIST (
    TODO_LIST_ID NUMBER AUTO_INCREMENT PRIMARY KEY,
    LIST_NAME VARCHAR2(50),
    USER_ID NUMBER,
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
);

CREATE TABLE TLA.TODO_LIST_ITEM (
    TODO_LIST_ITEM_ID NUMBER AUTO_INCREMENT PRIMARY KEY,
    TODO_LIST_ID NUMBER,
    ITEM_NAME VARCHAR2(50),
    ITEM_DESCRIPTION VARCHAR2(50),
    COMPLETED BOOLEAN NOT NULL DEFAULT FALSE,
    COMPLETED_AT TIMESTAMP,
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
);
